#!/bin/bash

umask 0022

date=$(date +"%a, %d %b %Y %T %z")

mkdir -p rpm-packages redhat/BUILD/usr/share/doc/podder redhat/RPMS

grep '^  \*' changelog.m4 |
(
  read discard version release discard

  m4 -D__VERSION__=$version -D__RELEASE__=$release                    podder.spec.m4 > redhat/podder.spec
  m4 -D__VERSION__=$version -D__DATE__="$date"                        podder.1.m4    > redhat/podder.1
  m4 -D__VERSION__=$version -D__DATE__="$date" -Ushift                podder.m4      > redhat/podder
  m4 -D__VERSION__=$version -D__RELEASE__=$release -D__DATE__="$date" changelog.m4   > redhat/Changelog
)

chmod +x redhat/podder

gzip --force --best redhat/podder.1

(
  cd redhat
  rpmbuild -bb podder.spec
)

mv redhat/RPMS/noarch/podder* rpm-packages
